import Head from "next/head";
import Image from "next/image";
import AffiliatesPage from "../_components/components/AffiliatesPage";

export default function Affiliates() {
    return (
        <>
            <Head>
                <title>Affiliates</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={``}>
                <AffiliatesPage />
            </main>
        </>
    );
}