import Head from "next/head";
import ExclusionPolicyPage from "../_components/components/ExclusionPolicyPage";

export default function Faq() {
    return (
        <>
            <Head>
                <title>Exclusion Policy</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={``}>
                <ExclusionPolicyPage />
            </main>
        </>
    );
}