import Head from "next/head";
import Image from "next/image";
import FaqPage from "../_components/components/FaqPage";

export default function Faq() {
    return (
        <>
            <Head>
                <title>Faq</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={``}>
                <FaqPage />
            </main>
        </>
    );
}