import Head from "next/head";
import GamePage2 from "../_components/components/GamePage2";

export default function Game2() {
    return (
        <>
            <Head>
                <title>Game2</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                {/*<link rel="icon" href="/favicon.ico" />*/}
            </Head>
            <main className={``}>
                <GamePage2 />
            </main>
        </>
    );
}