import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import CustomSlider from "../_components/view/Slider";
import LandingPage from "../_components/components/LandingPage";
import fetchData from "../utils/httpAction";

const inter = Inter({ subsets: ["latin"] });

export default function Home({bannersData=[]}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*<main className={`${styles.main} ${inter.className}`}>*/}
      <main className={``} style={{width: "100%"}}>
          <LandingPage bannersData={bannersData}/>
      </main>
    </>
  );
};

export async function getServerSideProps({ req }) {

    const host = req.headers.host;
    // Check if the request is using HTTPS
    const isHttps = req.headers['x-forwarded-proto'] === 'https';
    // Determine the protocol based on whether the request is HTTPS
    const protocol = isHttps ? 'https' : 'http';
    // Construct the API URL dynamically
    const hostUrl = `${protocol}://${host}`;
    // Fetch data from API
    let res =  await fetchData({  method : 'POST', endPoint:`${hostUrl}/api/common-api`});

    return {
        props: {
            bannersData : {...res},
        }
    };
}
