import Head from "next/head";
import Image from "next/image";
import ListingPage from "../_components/components/ListingPage";

export default function Setting() {
    return (
        <>
            <Head>
                <title>Listing Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={``}>
                <ListingPage />
            </main>
        </>
    );
}