import Head from "next/head";
import MyBetsPage from "../_components/components/MyBetsPage";

export default function MyDeposits() {
    return (
        <>
            <Head>
                <title>My-Bets</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={``}>
                <MyBetsPage type='deposit'/>
            </main>
        </>
    );
}