import Head from "next/head";
import Image from "next/image";
import OpenBetPage from "../_components/components/OpenBetPage";

export default function OpenBet() {
    return (
        <>
            <Head>
                <title>OpenBet</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={``}>
                <OpenBetPage />
            </main>
        </>
    );
}