import Head from "next/head";
import Image from "next/image";
import ProfitLossPage from "../_components/components/ProfitLossPage";

export default function ProfitLoss() {
    return (
        <>
            <Head>
                <title>Profile</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={``}>
                <ProfitLossPage />
            </main>
        </>
    );
}