import Head from "next/head";
import Image from "next/image";
import ReferralPage from "../_components/components/ReferralPage";

export default function Referral() {
    return (
        <>
            <Head>
                <title>Refferal</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={``}>
                <ReferralPage />
            </main>
        </>
    );
}