import Head from "next/head";
import Image from "next/image";
import WalletPage from "../_components/components/WalletPage";

export default function Wallet() {
    return (
        <>
            <Head>
                <title>Deposit Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={``}>
                <WalletPage />
            </main>
        </>
    );
}