import Head from "next/head";
import WithdrawalPage from "../_components/components/WithdrawalPage";

export default function Withdrawl() {
    return (
        <>
            <Head>
                <title>Withdrawal</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                {/*<link rel="icon" href="/favicon.ico" />*/}
            </Head>
            <main className={``}>
                <WithdrawalPage />
            </main>
        </>
    );
}